### PR TITLE
compile typescript to ES2017

### PR DESCRIPTION
**Pull request by maltek**
This needs further research/testing which I won't be able to do this year, but sending this out now while it's fresh in my mind.

ES2015 doesn't have async/await and the polyfills just make it so much harder to track what's going on in the code. Here's an example from juice-shop:

```javascript
function waitForClick(element) {
    return __awaiter(this, void 0, void 0, function* () {
        return yield new Promise((resolve) => {
            element.addEventListener('click', resolve);
        });
    });
}
```

Compiling to ES2018 we instead get this much simpler output:

```javascript
async function waitForClick(element) {
    return await new Promise((resolve) => {
        element.addEventListener('click', resolve);
    });
}
```

I haven't done full research yet which other language constructs this impacts - and how well we support all these. But my first quick testing looks promising.

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
Nice finding :+1: 
Lets keep this open here until @prabhu had a change to look at it too.

**Comment by prabhu** [comment]
I'm happy with the proposal. We may have to ensure all the AST based passes continue to work.

**Comment by maltek** [comment]
I took a deeper look at the transformations `tsc` does when compiling new code to an older language level:

ES2016:
  - `**`, `**=` exponentiation operators

ES 2017:
  - `async` functions
  - `super` keyword
  - scoping changes in catch clauses
  - `await` expressions

ES2018:
  - `async*` generators

ES2019:
  - catch clauses without variables

ES2020:
  - null-coalescing operator
  - optional expressions

ES2021:
  - `&&=`, `||=`, `??=` logical assignment operators

We can't deal with ES2021 yet. Up to that I see a bunch of things that should improve and nothing that would regress (except possibly some AST/string-based passes).

I'll update this PR for ES2020 and check how it behaves against SPTests tomorrow.

**Comment by maltek** [comment]
Ok, testing found a blocker for ES2018 and beyond which I overlooked before: we don't fully model the spread operator in object literals. (And we really want that to find prototype pollution vulns).

But ES2017 is good enough to get that simplification of async functions that I was originally looking for. We can do another bump when we get around to improve the spread operator.

**Review by prabhu — APPROVED** [review]

**Review by max-leuthaeuser — APPROVED** [review]

**Pull request merged**
