### PR TITLE
upgrade deps

### PR DESCRIPTION
**Pull request by mpollmeier**
note: this doesn't include the new HashUtil yet, it's mostly about fixing deprecation warnings driven by https://github.com/joernio/joern/pull/1303

### CODE REVIEW

**Review by ml86 — COMMENTED** [review]
That is not how the new fixture is supposed to be used.
Instead of writing `override val code = ""`
it is now supposed to be `val cpg = code("")`

**Comment by mpollmeier** [comment]
I know, and I started with that, but then I noticed that `DataFlowCodeToCpgSuite` has an `override def passes(cpg: Cpg)` (https://github.com/ShiftLeftSecurity/js2cpg/blob/master/src/test/scala/io/shiftleft/js2cpg/dataflow/DataFlowCodeToCpgSuite.scala#L26) which existed in the old `CodeToCpgFixture` but not in the new `Code2CpgFixture`. 

We do need to run some passes as a prerequisite for the dataflow tests though, so I added the logistics back into DataFlowCode2CpgSuite... Is there a better way to do this?

**Comment by max-leuthaeuser** [comment]
https://github.com/joernio/joern/blob/master/joern-cli/frontends/x2cpg/src/main/scala/io/joern/x2cpg/X2Cpg.scala#L210

Most of them are applied already. Only `OssDataFlow` is missing. Maybe override `Code2CpgFixture.code(...)` and apply it there? 
Afterwards, all `JSDataFlowTestN` could be merged to only one test running `val cpg = code("...")` individually.

**Comment by mpollmeier** [comment]
Hmm, overriding `Code2CpgFixture.code` doesn't seem nicer to me, mostly because there's actually two `def code` in there which we'd need to overload both, and what if someone later adds a third `def code`... 
@ml86 what's your thoughts on this?

**Comment by ml86** [comment]
I will provide the same extensibility options for the new base fixture class. Will put you on the PR.

**Comment by max-leuthaeuser** [comment]
@mpollmeier I adapted the data flow tests to the changes from @ml86 
Also `HashUtil.sha256` is re-used here now.

**Review by max-leuthaeuser — APPROVED** [review]

**Comment by mpollmeier** [comment]
thank you!

**Pull request merged**
