### PR TITLE
upgrade cpg

### PR DESCRIPTION
**Pull request by mpollmeier**

### CODE REVIEW

**Comment by mpollmeier** [comment]
```
[info] - should generate js files correctly for a simple Vue.js 2 project *** FAILED ***
[info]   List("src/main.js") did not contain the same elements as List("src/main.js", "src/App.vue") (TranspilationRunnerTest.scala:191)
```
@max-leuthaeuser would that be expected?

**Comment by max-leuthaeuser** [comment]
Thats most likely because you do not have npm installed locally.

But the actual problem is still (see the Github action):
```
[error] Uncaught exception when running io.shiftleft.js2cpg.dataflow.JSDataFlowTest1: java.lang.NoSuchMethodError: io.shiftleft.semanticcpg.language.package$.toMethod(Ljava/lang/Object;Lscala/Function1;)Loverflowdb/traversal/Traversal;
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: io.shiftleft.semanticcpg.language.package$.toMethod(Ljava/lang/Object;Lscala/Function1;)Loverflowdb/traversal/Traversal;````

**Comment by hubertp** [comment]
That is the same  error we see in integration tests

**Comment by mpollmeier** [comment]
yup i'm aware of that one, should get resolved via https://github.com/joernio/joern/pull/816

**Review by max-leuthaeuser — APPROVED** [review]

**Pull request merged**
