### PR TITLE
Update js to 22.1.0

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
Fixed issues with line separators.
Adjusted everything to the new GraalVM parser API (String -> TruffleString).

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
Yeah, looks like the GraalVM parser started to require at least Java 11 with this new version. I guess there is nothing much we can do about it right @mpollmeier ? As long as we are using Java 8 in codescience.

**Comment by mpollmeier** [comment]
Sounds like we need to be careful here. Just to make sure we're on the same boat, merging this would mean that any users of this frontend need to run it with JRE11+ right? 
js2cpg is used in Mesh and Ocular. 

Ocular currently requires JRE8 (note there's no `+` suffix), so merging this would break Ocular. 
@Ferada what's the situation for mesh at the moment? Do we already support multiple JVMs there? E.g. run java2cpg with JRE8 and j2cpg or c2cpg with JRE11?

So far we managed to dodge this bullet, but at some point (maybe that's now?) we need to choose between
a) upgrade java2cpg (more specifically our fork of soot) to java 11, or 
b) handle (and potentially ship) multiple JREs with both Mesh and Ocular.

That will also allow us to use the new C frontend in both Mesh and Ocular, which also requires JRE11+.

**Comment by max-leuthaeuser** [comment]
> Sounds like we need to be careful here. Just to make sure we're on the same boat, merging this would mean that any users of this frontend need to run it with JRE11+ right?

Exactly.

**Comment by Ferada** [comment]
> Ocular currently requires JRE8 (note there's no `+` suffix), so merging this would break Ocular. @Ferada what's the situation for mesh at the moment? Do we already support multiple JVMs there? E.g. run java2cpg with JRE8 and j2cpg or c2cpg with JRE11?

That only concerns `java2cpg` in mesh at the moment, since that's the only frontend for which we support running it on our servers apart from `csharp2cpg` - and we (can only) run it in-process, so it's the same JVM as the rest, yes.

> So far we managed to dodge this bullet, but at some point (maybe that's now?) we need to choose between a) upgrade java2cpg (more specifically our fork of soot) to java 11, or b) handle (and potentially ship) multiple JREs with both Mesh and Ocular.
> 
> That will also allow us to use the new C frontend in both Mesh and Ocular, which also requires JRE11+.

As far as I recall Markus' infos on that, upgrading Soot would be the more painful/expensive/impossible one.

**Comment by Ferada** [comment]
But this is also about the customer side actually, since we're shipping a JRE 8 in case we get a mismatched one from the customer (or none at all).

Would actually make it easier for us there if we can bump that to 11+?

**Comment by mpollmeier** [comment]
Ok so we actually have three cases:
1) `java2cpg` as part of mesh on our servers - this will need to continue running JRE8, no changes there
2) frontends invoked at customer site (via `sl`): sounds like we download the JRE on demand, is that right? Do we already support different JRE versions for that, e.g. JRE8 for `java2cpg`, JRE11 for `c2cpg` @Ferada ?
3) ocular: we currently require JRE8 - if we decide to merge this, we'll need to handle two JREs, either managed by the user, or shipped via the distribution, or downloaded on demand, similar to what `sl` does...

**Comment by Ferada** [comment]
>     2. frontends invoked at customer site (via `sl`): sounds like we download the JRE on demand, is that right? Do we already support different JRE versions for that, e.g. JRE8 for `java2cpg`, JRE11 for `c2cpg` @Ferada ?

No, we have a download for JRE 8 in case the customer doesn't have their own JVM, or has one of the wrong version. We don't have a download for JRE 11, nor do we ship `c2cpg` (only `js2cpg`, `kt2cpg` and `java2cpg` / `javasrc2cpg`).

>     3. ocular: we currently require JRE8 - if we decide to merge this, we'll need to handle two JREs, either managed by the user, or shipped via the distribution, or downloaded on demand, similar to what `sl` does...

You're welcome to use the same distribution channel of course so you don't have to bother ops more than necessary to have them on our CDN.

**Comment by mpollmeier** [comment]
status: no decision made yet, but @fabsx00 suggested yet another option to alleviate the need for JDK8 - more details to come

**Comment by max-leuthaeuser** [comment]
Superseded by: https://github.com/ShiftLeftSecurity/js2cpg/pull/188

**Pull request closed without merging**
