### PR TITLE
Configured different OS for PR tests

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
We had some issues with file paths on varying OS in the past. Let's make this a little bit safer here.

@mpollmeier Do we also have to adapt the release workflow test section somehow?

### CODE REVIEW

**Review by mpollmeier — DISMISSED** [review]
nice!

Personally I'm a big fan of stable versions, so I'd use specific os versions rather than `-latest`, since these are controlled from the outside. But that's up to you, really. 

I'd keep the release.yml as it is

**Comment by max-leuthaeuser** [comment]
Ok, looks like there are two problems here:
- does not even start testing on Windows (27s?!). Logs don't show anything.
- fails on MacOS maybe somewhere here: https://github.com/ShiftLeftSecurity/js2cpg/blob/master/cfgIntegrationTests/src/test/scala/io/shiftleft/js2cpg/cpg/passes/IntegrationTestFixture.scala#L60 (but also nothing in the logs)

**Comment by max-leuthaeuser** [comment]
Ok, I am out of ideas kinda.
Runs on Linux and MacOS now but still fails with some weird path issues on Windows. I guess the workflow runner for Windows (i.e., its shell) behaves not like I thought.

@mpollmeier Maybe you have some ideas. But it's not very urgent.

**Comment by mpollmeier** [comment]
hmm, no i don't really know and don't have a test machine, but my guess based on the error from the windows run
```
java.lang.RuntimeException: ERROR StatusLogger Invalid URL D:/a/js2cpg/js2cpg/src/main/resources/log4j2.xml
 java.net.MalformedURLException: unknown protocol: d
```
would be that it thinks that `D:/` is the protocol here... you could try something like `file:/d:/a`, maybe without the `:` and maybe with more `/` - fastest option would be to have this on a VM to play with...

**Comment by max-leuthaeuser** [comment]
I thinks thats not the actual problem here (just a related issue maybe).
js2cpg is called but fails with
`Error: Invalid <src> path: 'C:UsersRUNNER~1AppDataLocalTempjs2cpgCfgIntegrationTest7887264317305363739'`
Looks like the path is messed up somewhere.

**Comment by max-leuthaeuser** [comment]
This was a journey for sure.

@mpollmeier Now it runs on all platforms.

**Review by prabhu — APPROVED** [review]

**Comment by mpollmeier** [comment]
i admire your persistence with this :)

**Pull request merged**
