### PR TITLE
Updated org.graalvm.js parser

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
This requires at least Java 11 now to be run at customer side.

_Important_:
We need to wait with the merge until SL is ready.
Also, js2cpg-internal Manifest (see its build.sbt) needs to be adapted!

_Do not merge yet!_

### CODE REVIEW

**Comment by max-leuthaeuser** [comment]
See: https://github.com/ShiftLeftSecurity/js2cpg-internal/blob/master/build.sbt#L76

**Review by ursachec — DISMISSED** [review]

**Comment by max-leuthaeuser** [comment]
@ursachec So this could go in now right?
I will update dependencies here again on top.

**Comment by ursachec** [comment]
yup it can go in @max-leuthaeuser

**Review by ursachec — APPROVED** [review]

**Comment by ursachec** [comment]
but please hold off on the release for this one version

**Comment by max-leuthaeuser** [comment]
Sure.

**Pull request merged**
