### PR TITLE
Update dependencies and update to JDK 11

### PR DESCRIPTION
**Pull request by max-leuthaeuser**
Replaces:
 - https://github.com/ShiftLeftSecurity/js2cpg/pull/160
 - https://github.com/ShiftLeftSecurity/js2cpg/pull/187

@mpollmeier @Ferada  CS should be able to handle this update to JDK 11 now?

### CODE REVIEW

**Comment by Ferada** [comment]
> @mpollmeier @Ferada CS should be able to handle this update to JDK 11 now?

What exactly do you mean, does `js2cpg` require a JVM 1.11 installed on customer machines now, in contrast to before just requiring a JVM 1.8?

**Comment by max-leuthaeuser** [comment]
Yes, its the same discussion as in: https://github.com/ShiftLeftSecurity/js2cpg/pull/160
We do ship c2cpg now so I was thinking it should be no problem any longer.

**Comment by Ferada** [comment]
Either `c2cpg` runs fine with a JRE 1.8 or the customer will have an unpleasant experience if they try our download - we don't bundle a JRE 1.11 (yet).

Either way, nothing changed from that other discussion, if you need a JRE 1.11 now, then we need to find some resources to make a download available for it.

**Comment by max-leuthaeuser** [comment]
Both c2cpg (does require it already) and js2cpg (once this PR here would be in) require 1.11 to be build and run. Just tested this locally.
So I guess we need to put this on hold once again until Michael is back.

**Comment by Ferada** [comment]
https://github.com/ShiftLeftSecurity/product/issues/10790

**Comment by max-leuthaeuser** [comment]
@Ferada @mpollmeier So this could now be done as https://github.com/ShiftLeftSecurity/product/issues/10790 is finished?
I will do a new PR for this later as we have some conflicts here and a new graalvm js version is available anyway.

**Pull request closed without merging**
