### PR TITLE
Add quotes around dir for `ExternalCommand`

### PR DESCRIPTION
**Pull request by ursachec**

### CODE REVIEW

**Review by mpollmeier — DISMISSED** [review]
unsurprisingly, windows behaves a little differently...

**Comment by ursachec** [comment]
@mpollmeier Now it did the job

**Review by maltek — APPROVED** [review]
Seems a bit hacky at first, but the more I think about the more I think it's actually more robust in the end than changing a single call-site.

**Comment by ursachec** [comment]
I tried a few other things (like Java's _ProcessBuilder_), but there was always a catch in the end (e.g. the value for `PATH` not being passed around)

**Pull request merged**
